services:
  config-server:
    image: config-server
    ports:
      - '8888:8888'

  eureka-server:
    image: eureka-server
    ports:
      - '8761:8761'

  operation-an:
    image: operation
    ports:
      - '8081:8080'
    environment:
      APP_CONFIG_SERVER: config-server
      APP_EUREKA_SERVER: eureka-server
      SPRING_APPLICATION_NAME: an

  operation-sn:
    image: operation
    ports:
      - '8082:8080'
    environment:
      APP_CONFIG_SERVER: config-server
      APP_EUREKA_SERVER: eureka-server
      SPRING_APPLICATION_NAME: sn

  operation-mn:
    image: operation
    ports:
      - '8083:8080'
    environment:
      APP_CONFIG_SERVER: config-server
      APP_EUREKA_SERVER: eureka-server
      SPRING_APPLICATION_NAME: mn

  operation-dn:
    image: operation
    ports:
      - '8084:8080'
    environment:
      APP_CONFIG_SERVER: config-server
      APP_EUREKA_SERVER: eureka-server
      SPRING_APPLICATION_NAME: dn

  calculation:
    image: calculation
    ports:
      - '8080:8080'
    environment:
      APP_EUREKA_SERVER: eureka-server
