server:
  port: 8081

spring:
  application:
    name: an

  config:
    import: configserver:http://${APP_CONFIG_SERVER:localhost}:8888/

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${APP_EUREKA_SERVER:localhost}:8761/eureka
